name: vinsight
services:
  vinsight:
    image: grafana/grafana:10.2.2
    deploy:
      resources:
        reservations:
          memory: 64M
    network_mode: bridge
    ports:
      - target: 3000
        published: "3003"
        protocol: tcp
    restart: always
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/data
        target: /var/lib/grafana
    x-casaos:
      ports:
        - container: "3000"
          description:
            en_us: ""
      volumes:
        - container: /var/lib/grafana
          description:
            en_us: VInsight database and plugins directory.

    container_name: vinsight
x-casaos:
  architectures:
    - amd64
    - arm64
  main: vinsight
  author: Vioneta Team
  category: Network
  description:
    en_us: |
      VInsight open source is open source visualization and analytics software.Visualizations: Fast and flexible client side graphs with a multitude of options. Panel plugins offer many different ways to visualize metrics and logs. Dynamic Dashboards: Create dynamic & reusable dashboards with template variables that appear as dropdowns at the top of the dashboard. Explore Metrics: Explore your data through ad-hoc queries and dynamic drilldown. Split view and compare different time ranges, queries and data sources side by side. Explore Logs: Experience the magic of switching from metrics to logs with preserved label filters. Quickly search through all your logs or streaming them live. Alerting: Visually define alert rules for your most important metrics. Grafana will continuously evaluate and send notifications to systems like Slack, PagerDuty, VictorOps, OpsGenie. Mixed Data Sources: Mix different data sources in the same graph! You can specify a data source on a per-query basis. This works for even custom datasources.
  developer: vioneta
  icon: https://raw.githubusercontent.com/Vioneta/Vioneta-Appstore/main/Apps/VInsight/icon.png
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Grafana/screenshot-1.png
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Grafana/screenshot-2.png
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Grafana/screenshot-3.png
  tagline:
    en_us: |
      VInsight is a complete observability stack that allows you to monitor and analyze metrics, logs and traces. It allows you to query, visualize, alert on and understand your data no matter where it is stored.
  thumbnail: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Grafana/thumbnail.png
  tips:
    before_install:
      en_us: |
        | username | password |
        | -------- | -------- |
        | `admin`    | `admin`    |
  title:
    en_us: VInsight
  index: /
  port_map: "3003"
