name: vionetagro
services:
  vionetagro:
    environment:
      PGID: $PGID
      PUID: $PUID
      TZ: $TZ
    image: vioneta/vionetaos:latest
    deploy:
      resources:
        reservations:
          memory: 256M
    network_mode: host
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
    x-casaos:
      envs:
        - container: TZ
          description:
            en_us: TimeZone
        - container: PUID
          description:
            en_us: Run Vionet Agro as specified uid.
        - container: PGID
          description:
            en_us: Run Vionet Agro as specified gid.

      volumes:
        - container: /config
          description:
            en_us: Vioneta Agro config directory.
    container_name: vionetagro
x-casaos:
  architectures:
    - amd64
    - arm64
  main: vionetagro
  author: Vioneta Team
  category: Agriculture
  description:
    en_us: Smart precision agriculture platform that put local controll and dataprivacy at first
  developer: Vioneta Agro
  icon: https://raw.githubusercontent.com/Vioneta/Vioneta-Appstore/main/Apps/VioinetaAgro/icon.png
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/HomeAssistant/screenshot-1.jpg
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/HomeAssistant/screenshot-2.jpg
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/HomeAssistant/screenshot-3.jpg
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/HomeAssistant/screenshot-4.jpg
  tagline:
    en_us: Smart Agriculture Platform
  thumbnail: https://raw.githubusercontent.com/Vioneta/Vioneta-Appstore/main/Apps/VioinetaAgro/thumbnail.png
  tips: {}
  title:
    en_us: Vioneta Agro
  index: /
  port_map: "8123"
